package com.example.ai.transparency

/**
 * Klasifikace původu obsahu
 */
enum class ContentOriginType {
    VERIFIED_OMNIS_SYNTHETIC, // Obsah vygenerovaný naším systémem s platným vodoznakem AI Act
    EXTERNAL_WATERMARKED_AI,  // Cizí AI obsah s detekovaným vodoznakem
    UNVERIFIED_SUSPICIOUS_AI, // Podezřelý syntetický obsah bez povinného označení
    NATURAL_HUMAN             // Přirozený lidský text bez syntetických anomálií
}

data class OriginAnalysisReport(
    val originType: ContentOriginType,
    val confidence: Float,
    val detectedSoftwareAgent: String,
    val complianceStatus: String,
    val recommendation: String
)

/**
 * AiOriginDetector:
 * Detektor kontrolující označení a původ z cizích, externích či podezřelých nahrávek a textů.
 */
object AiOriginDetector {

    fun analyzeContent(text: String): OriginAnalysisReport {
        if (text.isBlank()) {
            return OriginAnalysisReport(
                originType = ContentOriginType.NATURAL_HUMAN,
                confidence = 1.0f,
                detectedSoftwareAgent = "None",
                complianceStatus = "N/A",
                recommendation = "Prázdný vstup."
            )
        }

        val extraction = AiSteganographyEngine.extractWatermark(text)

        if (extraction.hasValidWatermark) {
            return OriginAnalysisReport(
                originType = ContentOriginType.VERIFIED_OMNIS_SYNTHETIC,
                confidence = 1.0f,
                detectedSoftwareAgent = extraction.modelName,
                complianceStatus = "PLNĚ SHODNÉ (AI Act Čl. 50 odst. 2 splněn)",
                recommendation = "Obsah je řádně certifikován a opatřen neviditelným vodoznakem OMNIS."
            )
        }

        // Kontrola cizích syntetických indikátorů (např. C2PA tagy, typické syntetické vzorce)
        val hasExternalAiSignature = text.contains("Generated by AI", true) ||
                text.contains("c2pa", true) ||
                text.contains("DALL-E", true) ||
                text.contains("Midjourney", true)

        if (hasExternalAiSignature) {
            return OriginAnalysisReport(
                originType = ContentOriginType.EXTERNAL_WATERMARKED_AI,
                confidence = 0.90f,
                detectedSoftwareAgent = "External AI Model",
                complianceStatus = "EXTERNÍ OZNAČENÍ DETEKOVÁNO",
                recommendation = "Ověřte integritu licence a externí původ dat."
            )
        }

        // Kontrola podezřelého neoznačeného obsahu s vysokou perplexitou / anomáliemi
        val isSuspicious = text.contains("jako jazykový model", true) ||
                text.contains("nemám osobní pocity", true) ||
                text.contains("as an ai language model", true) ||
                text.contains("as an ai", true)

        if (isSuspicious) {
            return OriginAnalysisReport(
                originType = ContentOriginType.UNVERIFIED_SUSPICIOUS_AI,
                confidence = 0.85f,
                detectedSoftwareAgent = "Unverified LLM",
                complianceStatus = "NON-COMPLIANT (Chybí povinné označení dle AI Act)",
                recommendation = "Varování: Vstup nese znaky syntetického textu, avšak postrádá strojově čitelný vodoznak."
            )
        }

        return OriginAnalysisReport(
            originType = ContentOriginType.NATURAL_HUMAN,
            confidence = 0.95f,
            detectedSoftwareAgent = "Human Author",
            complianceStatus = "STANDARDNÍ LIDSKÝ OBSAH",
            recommendation = "Standardní zpracování bez nutnosti regulatorní intervence."
        )
    }
}
